#pragma once

#define CURVERSION_KEY		L"SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion"
#define CURBUILD_STR		L"CurrentBuild"
#define PRODUCTID_STR		L"ProductId"
#define PRODUCTNAME_STR		L"ProductName"
#define BUILDBRANCH_STR		L"BuildBranch"
#define BUILDGUID_STR		L"BuildGUID"
#define ORGANIZATION_STR	L"RegisteredOrganization"
#define OWNER_STR			L"RegisteredOwner"
#define SYSROOT_STR			L"SystemRoot"
#define RELEASEID_STR		L"ReleaseId"
#define EDITIONID_STR		L"EditionId"
#define INSTALLTYPE_STR		L"InstallationType"
#define CRIPTOGRAPHY_KEY	L"SOFTWARE\\Microsoft\\Cryptography"
#define MACHINEGUID_STR		L"MachineGuid"

#define OFFICE32_2003_KEY	L"SOFTWARE\\Microsoft\\Office\\11.0\\Registration"
#define OFFICE32_2007_KEY	L"SOFTWARE\\Microsoft\\Office\\12.0\\Registration"
#define OFFICE32_2010_KEY	L"SOFTWARE\\Microsoft\\Office\\14.0\\Registration"
#define OFFICE32_2013_KEY	L"SOFTWARE\\Microsoft\\Office\\15.0\\Registration"
#define OFFICE32_2016_KEY	L"SOFTWARE\\Microsoft\\Office\\16.0\\Registration"
#define OFFICE64_2003_KEY	L"SOFTWARE\\WOW6432Node\\Microsoft\\Office\\11.0\\Registration"
#define OFFICE64_2007_KEY	L"SOFTWARE\\WOW6432Node\\Microsoft\\Office\\12.0\\Registration"
#define OFFICE64_2010_KEY	L"SOFTWARE\\WOW6432Node\\Microsoft\\Office\\14.0\\Registration"
#define OFFICE64_2013_KEY	L"SOFTWARE\\WOW6432Node\\Microsoft\\Office\\15.0\\Registration"
#define OFFICE64_2016_KEY	L"SOFTWARE\\WOW6432Node\\Microsoft\\Office\\16.0\\Registration"
#define DIGITALPRODID_STR	L"DigitalProductId"

